include:
  - project: "shared/ci-utils"
    file: ".yarn.yml"

stages:
  - install
  - test
  - run

image: node:14.18.1-bullseye-slim

install:
  stage: install
  cache: !reference [.readWriteYarnCache]
  script:
    - yarn install --immutable --mode=skip-build

test:
  stage: test
  cache: !reference [.readOnlyYarnCache]
  script:
    - yarn run util:lint
    - yarn run util:validateTs

test-packed:
  stage: test
  cache: !reference [.readOnlyYarnCache]
  script:
    - yarn install
    - yarn build
    - yarn pack
    - tar -xzf triply-triplydb-*.tgz
    - cd ./package
    - cp -r ../node_modules ./
    - node ./lib/bin/triplydb.js --help

publish:
  stage: publish
  cache: !reference [.readOnlyYarnCache]
  script:
    - yarn install
    - yarn build
    - yarn publish --non-interactive
  only:
    refs:
      - /^v-.*$/
