enableTelemetry: false

logFilters:
  - code: YN0013 # ignore not-cached messages. Not interesting tbh
    level: discard
  - code: YN0002 # ignore peer-dependency errors. They are almost always false positives
    level: discard
  - code: YN0060 # ignore incompatible peer dependency errors. Almost always due to wrong package metadata
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
